---
- name: Install BIND9
  hosts: dns
  become: yes
  tasks:
    - name: Install BIND9
      ansible.builtin.package:
        name: bind9
        state: present
    - name: Bind9 UP
      service:
        name: bind9
        enabled: true
        state: started

- name: changing dns 
  hosts: all
  become: yes
  tasks:
    - import_tasks: tasks/set_dns.yml