---
- name: Update OS
  hosts: all
  become: yes

  tasks:
    - name: Update package
      ansible.builtin.package:
        name: '*'
        state: latest

- name: Install Apache2
  hosts: web
  become: yes

  tasks:
    - name: Install Apache2
      ansible.builtin.package:
        name: apache2
        state: present
